### PR TITLE
Perf opti

### PR DESCRIPTION
**Pull request by naluhh**

### CODE REVIEW

**Comment by niawag** [comment]
Hi Naluhh and thanks for your work! I'd be glad to optimize the speed for my display too. Is your code working?

I also have another question not directly related to your code, do you know how to sync/clone your commits to my Pi? I'm not really used to git CLI and I thought you might know how to do that!

EDIT : sorry, my head got mixed up, just had to clone your fork in another dir

**Comment by niawag** [comment]
Another question: is it possible to perform a partial refresh with your code?

**Comment by naluhh** [comment]
@niawag Hey, it's not possible as is, but it would be possible to do it.

**Comment by niawag** [comment]
Ok, I'll try to get a grasp at your code and see if I manage to do it!

**Comment by niawag** [comment]
Hi, I got a little bit of time to "play" with your code and understood that you designed it as a server waiting for a client to send the file(s). I'll write a client to test your work but do you have one that you could upload to this repo so other might use it easily?

**Pull request closed without merging**
